# Generated by Django 5.2.1 on 2025-05-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elFaro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='promociones/')),
                ('nombre', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
